name: CI Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: 'Checkout'
       uses: actions/checkout@v4
     - name: 'Setup node'
       uses: actions/setup-node@v4
       with:
         node-version: 20.11.1
     - name: 'Install dependencies'
       run: npm ci
       working-directory: ./Actividad1/devops_practice/
     - name: 'Run test'
       run:  npx jest --verbose
       working-directory: ./Actividad1/devops_practice/
     - name: 'Buil Docker image'
       run: docker build -t devops_practice .
       working-directory: ./Actividad1/devops_practice/
     - name: 'Run Docker container'
       working-directory: ./Actividad1/devops_practice/
       run: docker run -d -p 3000:3000 devops_practice
      
